### ISSUE TITLE
Code peer feedback week 1

### ISSUE THREAD

**Issue by HappyPantss** [johancvb/progressive-web-apps-2021#1]
Hey Johan, dit is mijn peer review op jouw code van de PWA opdracht.

1. Zodra ik je app run, dan krijg ik een ejs error zoals je al zei. Dat komt omdat je lijn 4 in team.ejs je HTML wel hebt gecommentarieerd, maar niet de EJS die daar bij hoort (te zien op lijn [3 en 9](https://github.com/johancvb/progressive-web-apps-2021/blob/e9c12643654a514954c4bac5bc54662929149cd9/views/teams.ejs#L3-L9)). 
Als je deze ook even weg haalt, heb je de error al niet meer. Dit kan je dus doen om te laten zien wat wel werkt, zonder iemand een error te geven.

2. Als ik die error weghaal, krijg ik de volgende error in mijn Console: 
![Image error](https://i.gyazo.com/2bba567c48f226a7470e4636ed76ed37.png)
Dat komt omdat je [icon link](https://github.com/johancvb/progressive-web-apps-2021/blob/e9c12643654a514954c4bac5bc54662929149cd9/views/partials/head.ejs#L9) niet klopt. Als je het veranderd naar `href="./img/nba.png"` moet het weer werken!

3. Voor de rest ziet alles er erg goed uit! Je componenten werken goed, je routes werken goed, je namen van de bestanden kloppen en je hebt geen oude bestanden erin staan. Keep going!

4. Alleen nog even je README toevoegen, en natuurlijk je functies, maar dat moet wel goedkomen!

Goodluck~~ Sergio/ HappyPantss 🐻

**Comment by johancvb** [comment]
Thanks voor je feedback man!
Heb het allemaal aangepast en het werkt gelukkig weer 😅

--Johan
