### ISSUE TITLE
.gitignore met node_modules

### ISSUE THREAD

**Issue by SamSlotemaker** [johancvb/progressive-web-apps-2021#2]
Voeg nog eventjes een .gitignore toe, waar je vervolgens node_modules aan toe voegt zodat deze niet naar github gepushd wordt, de map kan enorm groot worden namelijk

**Comment by johancvb** [comment]
Bedankt voor de tip, dat wist ik nog niet 😅.
Heb het aan mijn .gitignore toegevoegd, thanks man!

--Johan
